dist: trusty
language: php

cache:
  bundler: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
php:
- 7.1

addons:
  chrome: stable

before_install:
- phpenv config-rm xdebug.ini
- composer self-update
- composer --version
- google-chrome-stable --version

install:
# Add Composer's local bin directory to the PATH so that we will be running
# our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
- export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

# composer install should fail on bad patches.
- export COMPOSER_EXIT_ON_PATCH_FAILURE=1

# Create the MySQL database and add a user for testing.
- mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'lightning'@'localhost' IDENTIFIED BY 'lightning'; GRANT ALL ON drupal.* TO 'lightning'@'localhost';"

# Install the PECL YAML extension for strict parsing. yes is used to
# acknowledge all prompts.
- yes '' | pecl install yaml
# Tweak PHP configuration.
- echo 'max_execution_time = 120' >> drupal.php.ini;
- echo 'sendmail_path = /bin/true' >> drupal.php.ini;
- phpenv config-add drupal.php.ini
- phpenv rehash

# Build the Lightning code base with the latest dependencies.
- cd $HOME
- ls
- composer global require drupal/coder:^8.2.11 squizlabs/php_codesniffer:^2.7
#- phpcs $HOME/build/aweingarten/acquia_connector/ --standard=$HOME/.composer/vendor/drupal/coder/coder_sniffer/DrupalPractice
- phpcs $HOME/build/aweingarten/acquia_connector/ --standard=$HOME/.composer/vendor/drupal/coder/coder_sniffer/Drupal
