cloud_migration: []
identifier: ''
key: ''
network_address: 'https://rpc.acquia.com'
nspi_address: 'https://nspi.acquia.com'
subscription_data:
  - { active: false }
subscription_name: ''
use_cron: true
admin_priv: true
send_node_user: true
send_watchdog: true
module_diff_data: true
set_variables_override: true
debug: false
cron_interval: 30
verify_peer: false
migrate_files: true
hide_signup_messages: false
ah:
  network:
    key: false
    identifier: false
